name: Go CI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Build
      run: go build -v ./repository/employees_repository.go ./repository/employees_repository_test.go

    - name: Test
      run: go test -v ./repository/employees_repository.go ./repository/employees_repository_test.go
